### ISSUE TITLE
RF Events not triggering

### ISSUE THREAD

**Issue by gid204** [ale1800/ESP-360-REMOTE#2]
Before I buy one of these awesome products I decided to slap a DIY version together to confirm I can get my devices working as required before spending the money (I have most parts readily available).

I am not able to receive any RF codes using the home assistant event developer tool. Just wanted to check I am not doing anything wrong.

```yaml
substitutions:
  name: "esp-remote"
  room: "Lounge"
  friendly_name: "ESP Remote"
  project_name: "kaneo.esp_remote"
  project_version: "0.0.1"

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

logger:

api:

  services:
    - service: send_rf_raw
      variables:
        protocol_number: int
        raw_data: string
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            transmitter_id: RF_TX
            protocol: !lambda 'return  esphome::remote_base::RC_SWITCH_PROTOCOLS[protocol_number];'
            code: !lambda 'return raw_data;'

ota:

web_server:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: ".lan"

remote_receiver:
  - id: RF_RX
    pin: 
      number: GPIO5
      inverted: True
    dump: 
      - rc_switch
    tolerance: 35%
    filter: 200us
    idle: 4ms
    buffer_size: 10kb
    on_rc_switch:
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            protocol: !lambda 'return x.protocol;'
            code: !lambda 'return x.code;'

#Setting up IR and RF transmitters
remote_transmitter:
  - id: RF_TX
    pin: GPIO14
    carrier_duty_percent: 100%
```

Everything is connected up as per the config above.
I then go the developer tool events section and listen for `esphome.rf_code_received`:
![image](https://user-images.githubusercontent.com/7547109/230751477-6495e6aa-33c2-4301-acda-43555a443579.png)

I point my blinds RF (433MHz) remote and click some buttons but nothing pops up.

Obviously can't attest for the quality but these are the receivers/transmitters I bought and am using:
https://www.aliexpress.com/item/32735811163.html?spm=a2g0o.new_account_index.0.0.286725b9MZf6XG

I am using the Climax ESP32 POE board:
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

Thanks in advance!!

**Comment by ale1800** [comment]
Hello! Everything seems fine to me. 
There could be some things to modify, like tolerance, filter and idle.

One thing to try is to dump everything instead just rc_switch. Do that and let me know👍

Could you also share the model of the remote?

**Comment by gid204** [comment]
Thanks for the tip - after setting dump to 'all' I can now seem my codes coming through, they appear to be in 'pronto' format.
My new yaml (I changed to wifi just for an easier setup while debugging):
```yaml
substitutions:
  name: "esp-remote"
  room: "Lounge"
  friendly_name: "ESP Remote"
  project_name: "kaneo.esp_remote"
  project_version: "0.0.1"

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

logger:

api:


  services:
    - service: send_rf_raw
      variables:
        # protocol_number: int
        raw_data: string
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            transmitter_id: RF_TX
            # protocol: !lambda 'return  esphome::remote_base::RC_SWITCH_PROTOCOLS[protocol_number];'
            code: !lambda 'return raw_data;'

ota:

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: ".lan"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-Remote Fallback Hotspot"
    password: "K2I4dMrvo3RA"

captive_portal:

# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO17_OUT
#   phy_addr: 0
#   power_pin: GPIO12
#   domain: ".lan"

remote_receiver:
  - id: RF_RX
    pin: 
      number: GPIO5
      inverted: True
    dump:
      - pronto
    tolerance: 35%
    filter: 200us
    idle: 4ms
    buffer_size: 10kb
    on_pronto:
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            # protocol: !lambda 'return x.pronto_protocol;'
            code: !lambda 'return x.data;'

#Setting up IR and RF transmitters
remote_transmitter:
  - id: RF_TX
    pin: GPIO14
    carrier_duty_percent: 100%
```

It looks like [pronto](https://esphome.io/api/structesphome_1_1remote__base_1_1_pronto_data.html) struct doesn't have a 'protocol' data field as [rc_switch](https://esphome.io/api/structesphome_1_1remote__base_1_1_r_c_switch_data.html) does. It only expects a string. However, there is a separate [pronto_protocol](https://esphome.io/api/classesphome_1_1remote__base_1_1_pronto_protocol.html) class, but I'm not too sure if this is needed to be implemented in anyway?

So I am now receiving my codes:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7547109/230827861-32952d9c-7b26-4fcb-9941-16ceaf946dd6.png">

But when I try send this data using the transmitter nothing happens:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/7547109/230828013-7b74be5d-75e2-43e8-82d0-afd2f4bc20d3.png">

I have confirmed that all formatting from the raw code is removed.

I am quite knew to the rf_transmitter/receiver components (if that wasn't already obvious) so once again you're help is really appreciated!

**Comment by ale1800** [comment]
Great, so some progress.
Once you receive the pronto data, you should be able to transmit it with this action **remote_transmitter.transmit_pronto**
So add this service and try to transmit with it.

```yaml
    - service: send_rf_pronto
      variables:
        pronto_data: string
      then:
        - remote_transmitter.transmit_pronto:
            transmitter_id: RF_TX
            data: !lambda 'return pronto_data;'
```
